//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9164
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReferenceCobro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReferenceCobro.ZFI_WS_PAGOS")]
    public interface ZFI_WS_PAGOS {
        
        // CODEGEN: Generating message contract since the operation ZFI_WS_INTERFASE_PAGOS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZFI_WS_PAGOS:ZFI_WS_INTERFASE_PAGOSRequest" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse1 ZFI_WS_INTERFASE_PAGOS(ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_WS_INTERFASE_PAGOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSFI_WS_PAGOS[] zSFI_WS_PAGOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSFI_WS_PAGOS[] ZSFI_WS_PAGOS {
            get {
                return this.zSFI_WS_PAGOSField;
            }
            set {
                this.zSFI_WS_PAGOSField = value;
                this.RaisePropertyChanged("ZSFI_WS_PAGOS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSFI_WS_PAGOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cIA_CLIENTEField;
        
        private string pAISField;
        
        private string rNCField;
        
        private string fECHA_PAGOField;
        
        private string nUMERO_PAGOField;
        
        private string bANCOField;
        
        private string nUM_CUENTAField;
        
        private string mONTO_PAGADOField;
        
        private string mONEDA_PAGOField;
        
        private string aNTICIPOField;
        
        private string rECIBOField;
        
        private string sU_DOCUMENTOField;
        
        private string fECHAField;
        
        private string cOMPROBANTE_FISCALField;
        
        private string mONEDAField;
        
        private string tOTAL_RECIBOField;
        
        private string dESCUENTOSField;
        
        private string vALOR_NETOField;
        
        private string nUM_CONTENEDORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CIA_CLIENTE {
            get {
                return this.cIA_CLIENTEField;
            }
            set {
                this.cIA_CLIENTEField = value;
                this.RaisePropertyChanged("CIA_CLIENTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PAIS {
            get {
                return this.pAISField;
            }
            set {
                this.pAISField = value;
                this.RaisePropertyChanged("PAIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RNC {
            get {
                return this.rNCField;
            }
            set {
                this.rNCField = value;
                this.RaisePropertyChanged("RNC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FECHA_PAGO {
            get {
                return this.fECHA_PAGOField;
            }
            set {
                this.fECHA_PAGOField = value;
                this.RaisePropertyChanged("FECHA_PAGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NUMERO_PAGO {
            get {
                return this.nUMERO_PAGOField;
            }
            set {
                this.nUMERO_PAGOField = value;
                this.RaisePropertyChanged("NUMERO_PAGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BANCO {
            get {
                return this.bANCOField;
            }
            set {
                this.bANCOField = value;
                this.RaisePropertyChanged("BANCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NUM_CUENTA {
            get {
                return this.nUM_CUENTAField;
            }
            set {
                this.nUM_CUENTAField = value;
                this.RaisePropertyChanged("NUM_CUENTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MONTO_PAGADO {
            get {
                return this.mONTO_PAGADOField;
            }
            set {
                this.mONTO_PAGADOField = value;
                this.RaisePropertyChanged("MONTO_PAGADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MONEDA_PAGO {
            get {
                return this.mONEDA_PAGOField;
            }
            set {
                this.mONEDA_PAGOField = value;
                this.RaisePropertyChanged("MONEDA_PAGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ANTICIPO {
            get {
                return this.aNTICIPOField;
            }
            set {
                this.aNTICIPOField = value;
                this.RaisePropertyChanged("ANTICIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string RECIBO {
            get {
                return this.rECIBOField;
            }
            set {
                this.rECIBOField = value;
                this.RaisePropertyChanged("RECIBO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SU_DOCUMENTO {
            get {
                return this.sU_DOCUMENTOField;
            }
            set {
                this.sU_DOCUMENTOField = value;
                this.RaisePropertyChanged("SU_DOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string COMPROBANTE_FISCAL {
            get {
                return this.cOMPROBANTE_FISCALField;
            }
            set {
                this.cOMPROBANTE_FISCALField = value;
                this.RaisePropertyChanged("COMPROBANTE_FISCAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
                this.RaisePropertyChanged("MONEDA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string TOTAL_RECIBO {
            get {
                return this.tOTAL_RECIBOField;
            }
            set {
                this.tOTAL_RECIBOField = value;
                this.RaisePropertyChanged("TOTAL_RECIBO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string DESCUENTOS {
            get {
                return this.dESCUENTOSField;
            }
            set {
                this.dESCUENTOSField = value;
                this.RaisePropertyChanged("DESCUENTOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string VALOR_NETO {
            get {
                return this.vALOR_NETOField;
            }
            set {
                this.vALOR_NETOField = value;
                this.RaisePropertyChanged("VALOR_NETO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string NUM_CONTENEDOR {
            get {
                return this.nUM_CONTENEDORField;
            }
            set {
                this.nUM_CONTENEDORField = value;
                this.RaisePropertyChanged("NUM_CONTENEDOR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSFI_WS_MSG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mENSAJEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSFI_WS_PAGOS_RESULTADO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rESULTADOField;
        
        private ZSFI_WS_MSG[] mENSAJESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSFI_WS_MSG[] MENSAJES {
            get {
                return this.mENSAJESField;
            }
            set {
                this.mENSAJESField = value;
                this.RaisePropertyChanged("MENSAJES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_WS_INTERFASE_PAGOSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSFI_WS_PAGOS_RESULTADO rESULTADOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZSFI_WS_PAGOS_RESULTADO RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
                this.RaisePropertyChanged("RESULTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFI_WS_INTERFASE_PAGOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOS ZFI_WS_INTERFASE_PAGOS;
        
        public ZFI_WS_INTERFASE_PAGOSRequest() {
        }
        
        public ZFI_WS_INTERFASE_PAGOSRequest(ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOS ZFI_WS_INTERFASE_PAGOS) {
            this.ZFI_WS_INTERFASE_PAGOS = ZFI_WS_INTERFASE_PAGOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFI_WS_INTERFASE_PAGOSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse ZFI_WS_INTERFASE_PAGOSResponse;
        
        public ZFI_WS_INTERFASE_PAGOSResponse1() {
        }
        
        public ZFI_WS_INTERFASE_PAGOSResponse1(ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse ZFI_WS_INTERFASE_PAGOSResponse) {
            this.ZFI_WS_INTERFASE_PAGOSResponse = ZFI_WS_INTERFASE_PAGOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ZFI_WS_PAGOSChannel : ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_PAGOS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ZFI_WS_PAGOSClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_PAGOS>, ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_PAGOS {
        
        public ZFI_WS_PAGOSClient() {
        }
        
        public ZFI_WS_PAGOSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZFI_WS_PAGOSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFI_WS_PAGOSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFI_WS_PAGOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse1 ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_PAGOS.ZFI_WS_INTERFASE_PAGOS(ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSRequest request) {
            return base.Channel.ZFI_WS_INTERFASE_PAGOS(request);
        }
        
        public ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse ZFI_WS_INTERFASE_PAGOS(ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOS ZFI_WS_INTERFASE_PAGOS1) {
            ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSRequest inValue = new ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSRequest();
            inValue.ZFI_WS_INTERFASE_PAGOS = ZFI_WS_INTERFASE_PAGOS1;
            ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_INTERFASE_PAGOSResponse1 retVal = ((ConsoleApplication1.ServiceReferenceCobro.ZFI_WS_PAGOS)(this)).ZFI_WS_INTERFASE_PAGOS(inValue);
            return retVal.ZFI_WS_INTERFASE_PAGOSResponse;
        }
    }
}
