//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessObjects.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string buttonSearch {
            get {
                return ResourceManager.GetString("buttonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha es invalida.
        /// </summary>
        public static string DateInitialization {
            get {
                return ResourceManager.GetString("DateInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un formato valido de correo.
        /// </summary>
        public static string EmailAddressErrorMessage {
            get {
                return ResourceManager.GetString("EmailAddressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La informacion digitada excede el limite del campo.
        /// </summary>
        public static string MaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  necesita cerrar otro..
        /// </summary>
        public static string MessageCloseForm {
            get {
                return ResourceManager.GetString("MessageCloseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue eliminado.
        /// </summary>
        public static string MessageDeletedFields {
            get {
                return ResourceManager.GetString("MessageDeletedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido una excepción.
        /// </summary>
        public static string MessageExcepcion {
            get {
                return ResourceManager.GetString("MessageExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando.
        /// </summary>
        public static string MessageFinding {
            get {
                return ResourceManager.GetString("MessageFinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localización .
        /// </summary>
        public static string MessageLocalization {
            get {
                return ResourceManager.GetString("MessageLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no es válida!!.
        /// </summary>
        public static string MessageLocalizationNotValidate {
            get {
                return ResourceManager.GetString("MessageLocalizationNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El menú que se solicita no esta disponible, favor contactar con el departamento de tecnología..
        /// </summary>
        public static string MessageMenuWithoutServices {
            get {
                return ResourceManager.GetString("MessageMenuWithoutServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso!!!.
        /// </summary>
        public static string MessageNotice {
            get {
                return ResourceManager.GetString("MessageNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para abrir el formulario.
        /// </summary>
        public static string MessageOpenForm {
            get {
                return ResourceManager.GetString("MessageOpenForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos fueron salvados.
        /// </summary>
        public static string MessageSavedFields {
            get {
                return ResourceManager.GetString("MessageSavedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string navigationBarItemCliente {
            get {
                return ResourceManager.GetString("navigationBarItemCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe introducir un formato valido de telefono.
        /// </summary>
        public static string PhoneErrorMessage {
            get {
                return ResourceManager.GetString("PhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo no puede estar en blanco.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string textBoxSearch {
            get {
                return ResourceManager.GetString("textBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string toolBarButtonBuscar {
            get {
                return ResourceManager.GetString("toolBarButtonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string toolBarButtonCancelar {
            get {
                return ResourceManager.GetString("toolBarButtonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string toolBarButtonEditar {
            get {
                return ResourceManager.GetString("toolBarButtonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string toolBarButtonEliminar {
            get {
                return ResourceManager.GetString("toolBarButtonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string toolBarButtonExcel {
            get {
                return ResourceManager.GetString("toolBarButtonExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string toolBarButtonImprimir {
            get {
                return ResourceManager.GetString("toolBarButtonImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string toolBarButtonInfo {
            get {
                return ResourceManager.GetString("toolBarButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string toolBarButtonNuevo {
            get {
                return ResourceManager.GetString("toolBarButtonNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string toolBarButtonSalvar {
            get {
                return ResourceManager.GetString("toolBarButtonSalvar", resourceCulture);
            }
        }
    }
}
