//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9164
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReferencePrice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO")]
    public interface ZSD_SHCAD_BUSCAR_PRECIO {
        
        // CODEGEN: Generating message contract since the operation ZSD_BUSCAR_PRECIOS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_SHCAD_BUSCAR_PRECIO:ZSD_BUSCAR_PRECIOS" +
            "Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse1 ZSD_BUSCAR_PRECIOS(ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_BUSCAR_PRECIOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSDES_MATERIALES[] p_MATNRField;
        
        private string p_TAXNUMField;
        
        private string p_VKORGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDES_MATERIALES[] P_MATNR {
            get {
                return this.p_MATNRField;
            }
            set {
                this.p_MATNRField = value;
                this.RaisePropertyChanged("P_MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string P_TAXNUM {
            get {
                return this.p_TAXNUMField;
            }
            set {
                this.p_TAXNUMField = value;
                this.RaisePropertyChanged("P_TAXNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string P_VKORG {
            get {
                return this.p_VKORGField;
            }
            set {
                this.p_VKORGField = value;
                this.RaisePropertyChanged("P_VKORG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDES_MATERIALES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private int qTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
                this.RaisePropertyChanged("QTY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDES_PRECIOS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private string mEINSField;
        
        private decimal cOND_VALUEField;
        
        private string wAERKField;
        
        private string bTRTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal COND_VALUE {
            get {
                return this.cOND_VALUEField;
            }
            set {
                this.cOND_VALUEField = value;
                this.RaisePropertyChanged("COND_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string WAERK {
            get {
                return this.wAERKField;
            }
            set {
                this.wAERKField = value;
                this.RaisePropertyChanged("WAERK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BTRTL {
            get {
                return this.bTRTLField;
            }
            set {
                this.bTRTLField = value;
                this.RaisePropertyChanged("BTRTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_BUSCAR_PRECIOSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZSDES_PRECIOS[] iT_PRECIOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDES_PRECIOS[] IT_PRECIOS {
            get {
                return this.iT_PRECIOSField;
            }
            set {
                this.iT_PRECIOSField = value;
                this.RaisePropertyChanged("IT_PRECIOS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_BUSCAR_PRECIOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOS ZSD_BUSCAR_PRECIOS;
        
        public ZSD_BUSCAR_PRECIOSRequest() {
        }
        
        public ZSD_BUSCAR_PRECIOSRequest(ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOS ZSD_BUSCAR_PRECIOS) {
            this.ZSD_BUSCAR_PRECIOS = ZSD_BUSCAR_PRECIOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_BUSCAR_PRECIOSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse ZSD_BUSCAR_PRECIOSResponse;
        
        public ZSD_BUSCAR_PRECIOSResponse1() {
        }
        
        public ZSD_BUSCAR_PRECIOSResponse1(ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse ZSD_BUSCAR_PRECIOSResponse) {
            this.ZSD_BUSCAR_PRECIOSResponse = ZSD_BUSCAR_PRECIOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ZSD_SHCAD_BUSCAR_PRECIOChannel : ConsoleApplication1.ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ZSD_SHCAD_BUSCAR_PRECIOClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO>, ConsoleApplication1.ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO {
        
        public ZSD_SHCAD_BUSCAR_PRECIOClient() {
        }
        
        public ZSD_SHCAD_BUSCAR_PRECIOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZSD_SHCAD_BUSCAR_PRECIOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_SHCAD_BUSCAR_PRECIOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_SHCAD_BUSCAR_PRECIOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse1 ConsoleApplication1.ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO.ZSD_BUSCAR_PRECIOS(ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSRequest request) {
            return base.Channel.ZSD_BUSCAR_PRECIOS(request);
        }
        
        public ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse ZSD_BUSCAR_PRECIOS(ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOS ZSD_BUSCAR_PRECIOS1) {
            ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSRequest inValue = new ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSRequest();
            inValue.ZSD_BUSCAR_PRECIOS = ZSD_BUSCAR_PRECIOS1;
            ConsoleApplication1.ServiceReferencePrice.ZSD_BUSCAR_PRECIOSResponse1 retVal = ((ConsoleApplication1.ServiceReferencePrice.ZSD_SHCAD_BUSCAR_PRECIO)(this)).ZSD_BUSCAR_PRECIOS(inValue);
            return retVal.ZSD_BUSCAR_PRECIOSResponse;
        }
    }
}
